添加damang数据库插件
nacos-group/nacos-plugin pull request #24
Opened 2023-04-25 11:39 UTC by xiaoyonghaoe

2023-05-12 01:32 UTC, KomachiSion commented
@xiaoyonghaoe The datasource plugin api has changed in 2.3.0, Can you adapt for 2.3.0 new plugin api?

2023-05-17 07:46 UTC, xiaoyonghaoe commented
> 

简单测试了一下 没有发现问题

2023-05-25 09:43 UTC, KomachiSion requested changes
我看Mapper的部分基本都是用的Base的SQL， Base SQL应该是 SQL92的通用语句， dameng数据库这边都能兼容吗？

2023-05-25 09:43 UTC, KomachiSion commented on nacos-datasource-plugin-ext/nacos-dm-datasource-plugin-ext/src/main/resources/sql-error-codes.xml
这个文件是做什么的？

2023-05-25 09:43 UTC, KomachiSion commented on nacos-datasource-plugin-ext/nacos-dm-datasource-plugin-ext/src/main/resources/schema/nacos-dm.sql
这个文件是用来简表的吗？ 我看下面还有很多插入的SQL

2023-05-25 10:48 UTC, xiaoyonghaoe commented on nacos-datasource-plugin-ext/nacos-dm-datasource-plugin-ext/src/main/resources/schema/nacos-dm.sql
已经删除了脏的插入语句

2023-05-25 10:50 UTC, xiaoyonghaoe commented on nacos-datasource-plugin-ext/nacos-dm-datasource-plugin-ext/src/main/resources/sql-error-codes.xml
此文件主要做dameng数据库错误码与spring异常类的映射关系
由于使用者可能会添加多个数据库插件 当添加dameng插件时 却不使用dameng数据库
可能会导致此文件覆盖掉spring的默认文件，所以这里冗余了多个数据库的配置

2023-05-26 05:44 UTC, KomachiSion approved these changes

2023-05-26 05:45 UTC, merged