修复dm数据库文件模式错误
nacos-group/nacos-plugin pull request #36
Opened 2024-03-06 06:46 UTC by timyuer

fix: #35

2024-03-06 06:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nacos-group/nacos-plugin?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nacos-group/nacos-plugin?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nacos-group/nacos-plugin?pullRequest=36) it.</sub>

2024-03-12 05:58 UTC, timyuer commented
@KomachiSion @li-xiao-shuang Can you help with the review？

2024-06-04 02:25 UTC, KomachiSion requested changes
只有这个小问题修复一下。

2024-06-04 02:25 UTC, KomachiSion commented on nacos-datasource-plugin-ext/nacos-dm-datasource-plugin-ext/pom.xml
> +<!--            <scope>system</scope>-->
如果确认不需要，建议直接移除不是注释掉

2024-06-04 02:33 UTC, timyuer commented
> 只有这个小问题修复一下。

@KomachiSion 
Updated according to comments, Thanks for your review.

2026-03-02 10:08 UTC, merged